[package]
name = "calcium-polynomial-monic-observe"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
hyperreal = { path = "../polynomial-monic-trial/hyperreal" }
hyperlimit = { path = "../polynomial-monic-trial/hyperlimit" }
hypersolve = { path = "../polynomial-monic-trial/hypersolve" }
[[bin]]
name = "calcium-polynomial-monic-observe"
path = "../polynomial-closure-observe.rs"
