.\" Copyright (c) Keith Briggs (Keith.Briggs@bt.com)
.TH "xr-1.1" "C library" "Keith Briggs"
.SH NAME
.sp
xr \- C library of exact real functions
.sp
.SH SYNOPSIS
.sp
.BI "#include ""xr.h"" "
.sp
.BI "int xr_get_b ();"
.br
.BI "void xr_set_b (int b);"
.sp
.BI "xr_t xr_init (long a, long b);"
.br
.BI "xr_t xr_set (const xr_t a);"
.br
.BI "void xr_free (const xr_t x);"
.sp
.BI "xr_t xr_abs (const xr_t x);"
.br
.BI "xr_t xr_neg (const xr_t x);"
.br
.BI "xr_t xr_recip (const xr_t x);"
.br
.BI "xr_t xr_sqrt (const xr_t x);"
.br
.BI "xr_t xr_sqr (const xr_t x);"
.br
.sp
.BI "xr_t xr_iadd (const long x, const xr_t y);"
.br
.BI "xr_t xr_isub (const long x, const xr_t y);"
.br
.BI "xr_t xr_imul (const long x, const xr_t y);"
.br
.sp
.BI "xr_t xr_subi (const xr_t x, const long y);"
.br
.BI "xr_t xr_divi (const xr_t x, const long y);"
.br
.BI "xr_t xr_powi (const xr_t xx, long n);"
.br
.BI "xr_t xr_root (const xr_t xx, long n);"
.sp
.BI "xr_t xr_add (const xr_t x, const xr_t y);"
.br
.BI "xr_t xr_sub (const xr_t x, const xr_t y);"
.br
.BI "xr_t xr_mul (const xr_t x, const xr_t y);"
.br
.BI "xr_t xr_div (const xr_t x, const xr_t y);"
.sp
.BI "xr_t xr_pi (void);"
.br
.BI "xr_t xr_exp (const xr_t x);"
.sp
.br
.BI "int xr_cmp (xr_t a, xr_t b);"
.br
.BI "long xr_log2_bound(xr_t x);"
.br
.BI "xr_t xr_near_int(const xr_t x);"
.br
.BI "void xr_dotdump (const char* dotfilename, const xr_t x, const int showcache);"
.br
.BI "double xr_get_d (const xr_t x, int n);"
.br
.BI "int xr_print (const xr_t x, const int n);"
.br
.BI "int xr_print_nl (const xr_t x, const int n);"
.br
.BI "void xr_timing (int k);"
.sp
.SH DESCRIPTION
.sp
The functions in the
.B xr
family manipulate
.I exact real numbers
using the scaled-integer representation invented by Boehm et al. [1] and
developed further by M\o"e\'"nissier-Morain [2].  They are intended for
proving inequalities between quantities computed from exact (i.e. rational)
data, something impossible with floating-point arithmetic.  In this system a
real
.EQ
x  hat
.EN
is represented internally by a function
.EQ
x: {Z sup +} -> Z 
.EN
which satisfies (for all
.EQ
n>=0
.EN
and for some fixed integer
.EQ
b>0
.EN
)
.ce
.EQ
size 12 { left |  2 sup {b n} {x  hat} - x(n) right | < 1 }
.EN
The various arithmetic functions maintain this inequality through all
operations.
.sp
All computations depend on the parameter b (the `granularity')
which by default is 2.   It can be set with xr_set_b(b) before
initialization any exact reals, but should then not be changed again
until the end of the computation.   Values of b such as 1,3,4,5 may be faster
on some problems, but all output should be the same.
.sp
.SH FUNCTIONS
.sp
.SS Initialization and clearing
.TP
.B "xr_set_b(b), xr_get_b(), xr_init(n,d)"
Set and get the parameter b (typically 2,3,4; default if not set is 2) and 
initialize an exact real to the rational n/d.
.TP
.B xr_free(x)
frees x but not the exact reals it depends on.   This can lead
to unreferenced and hence unreclaimable memory.
.SS Unary arithmetic operations
.TP 
.B "xr_abs(x), xr_neg(x), xr_recip(x), xr_sqr(x), xr_sqrt(x), xr_root(x,n)"
Absolute value, negative, reciprocal, square, square root, 
.ft I 
n
.ft
th root 
.SS Bunary arithmetic operations
(i.e. Semi-unary: first argument long, second argument xr_t)
.TP 
.B "xr_iadd(n,x), xr_isub(n,s), xr_imul(n,s)"
e.g. iadd adds a long to an xr_t, and will be faster than converting the long to an xr.
.SS Ubnary arithmetic operations
(i.e. first argument xr_t, second argument long)
.TP
.B "xr_divi(x,y), xr_powi(x,n), xr_root(x,n)"
Divide by integer, integer power, integer root.
.SS Binary arithmetic operations
.TP
.B "xr_add(x,y), xr_sub(x,y), xr_mul(x,y), xr_div(x,y)"
Add, subtract, multiply, divide two exact reals.   
.SS Other arithmetic operations
.TP
.B xr_cmp(x,y)
Initiates evaluation of x and y, and terminates when it can decide that 
they are unequal, returning 1 for x>y and -1 for x<y.   It 
.BI never
terminates if x=y.    
.TP
.B xr_log2_bound(x)
returns an integer k such that 
.EQ
| x / {2 sup k} | < 1
.EN
It is safe to call with any argument.
.TP
.B xr_near_int(x)
return either the floor or ceiling of an xr_t (this is a typical 
multivalued exact real function - the floor and ceiling themselves 
are not computable).  It is safe to call with any argument.
.SS Transcendental functions
.TP
.B "xr_exp(x), xr_pi(void)"
Others are under development.
.SS Output
.TP
.B "xr_get_d(x,n), char* xr_get_str(x,n), xr_print(x,n), xr_print_nl(x,n)"
These functions try to get n correct decimals of x, but do not 
guarantee correctness.   xr_get_d uses double-precision arithmetic
internally and so is subject to exponent range limitations.
These functions do not terminate if x=0.
.TP
.B xr_dotdump(dotfilename,x,showcache)
writes a file 
.BI dotfilename.dot
in the graphviz [4] dot format, for conversion to a 
graphic represention of the internal data structure.
.SH NOTES
.sp
The underlying large-integer arithmetic is done with the gmp library [3].
There is no floating-point arithmetic used anywhere except in the xr_get_d and 
pi functions.
See the programs ..._test.c for examples.
A simple C++ interface is defined in
.B xr++.h
It just defines one class xr and overloads the basic operators.
The function names are the same, but without the xr_ prefix.
.sp
.SH EXAMPLE C APPLICATION
.ft I
/* gcc -O example.c xr.o -lm -lgmp -o example */
.br
#include "xr.h"  
.br
int main() { /* test whether exp(pi*sqrt(163)) is integral */ 
  xr_t x;
  x=xr_exp(xr_mul(xr_pi(),xr_sqrt(xr_init(163,1))));
  printf("%d\\n",xr_cmp(x,xr_near_int(x)));
  return 0;
.br
}
.ft
.SH EXAMPLE C++ APPLICATION
.ft I
// g++ -O example.cc xr.o -lm -lgmp -o example
.br
#include "xr++.h"  
.br
int main() { // test whether exp(pi*sqrt(163)) is integral
  xr x;
  x=exp(pi()*sqrt(xr(163)));
  cout<<(x>near_int(x))<<endl;
  return 0;
.br
}
.ft
.SH "CONFORMING TO"
.sp
ANSI C (I hope)
.sp
.SH AUTHOR
.sp
Keith Briggs (Keith.Briggs@bt.com)
.sp
.SH HISTORY
.sp
Version 1.0 2003 March 31.    I have written other implementations in python
and C++.   The aim of this C version is faster performance and greater
ease of integration into existing code.
.sp
.SH BUGS
Of course.
.sp
.SH REFERENCES
.sp
[1] http://portal.acm.org/citation.cfm?doid=319838.319860
.br
[2] http://www-calfor.lip6.fr/~vmm/arith_english.html
.br
[3] http://www.swox.com/gmp
.br
[4] http://www.research.att.com/sw/tools/graphviz/
