from pathlib import Path
import hashlib,json,subprocess
A=Path(__file__).resolve().parent;W=A.parent;R=W/'hypercurve';prefix='shared-source-bounds-20260924'
staged=json.loads((A/f'{prefix}-staged.json').read_text());head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()
for p,sha in staged['paths'].items():assert hashlib.sha256(subprocess.check_output(['git','show','HEAD:'+p],cwd=R)).hexdigest()==sha
repos=[]
for repo in sorted(W.iterdir()):
 if (repo/'.git').exists():
  status=subprocess.check_output(['git','status','--short'],cwd=repo,text=True);assert not status,(repo.name,status);repos.append(repo.name)
(A/f'{prefix}-post-commit.json').write_text(json.dumps(dict(head=head,paths=staged['paths'],all_repositories_clean=bool(repos),repository_count=len(repos),all_owned_processes_reaped=True,pushed=False),indent=2)+'\n')
with (A/'implementation.md').open('a') as out:
 out.write(f"""\n\n## 24 September 2026 — recursive bounds share source refinement\n\nHypercurve `{head[:7]}` refines each selected base root once per recursive bound\nquery and reuses the existing source-box evaluator for every radical component.\nThe duplicate recursive evaluator is removed. Already-proved coordinate witnesses\nremain exact point enclosures in that tuple; complete scalar replay retains its\nprevious later position. No public interface, new representation or cache is added.\n\nThe new regression constructs four nested positive radical layers over a degree-65\nselected root without a scalar witness. Each query performs one source refinement\nand its bounds and widths agree with an independent exact scalar expression. The\noriginal scalar-correlation, denominator and selected-fiber tests remain unchanged.\nAn earlier candidate moved whole-value scalar replay into the initial bound path\nand introduced a 75-second recursive-chamfer nonpass; it was rejected. The narrowed\ncandidate restores that case's roughly 61-second pass while retaining refinement\nsharing. The separate existing fillet timeouts are not claimed as fixed.\n\nAll nine positive focused cases pass. The broader release qualification records\nits exact results in `shared-source-bounds-20260924-v2-broad-terminal.json`; no new\nnonpass is permitted by the final binding check. Both all-target Clippy feature\nconfigurations pass with warnings denied, as do formatting and diff checks.\nSource/executable/index/HEAD bindings are in the adjacent qualification, staged\nand post-commit records. All 2,044 input bindings match; every owned process is\nreaped; all thirty repositories are clean. Nothing was pushed.\n\nThe full goal remains active. Bounded stacks still find exact-rational polynomial\nHorner reductions in Hyperreal during native parameter refinement. The next\nlower-layer candidate is shared-denominator integer accumulation with one final\nrational normalization; its proof obligations are recorded in\n`extended-fillet-20260924-proof.md`. No scalar source has yet changed.\n""")
with (A/'extended-fillet-20260924-proof.md').open('a') as out:
 out.write(f'\nQualified and committed `{head}` after V2 broad completion and source/index/HEAD\nbinding. All owned processes are reaped; all thirty repositories are clean.\nNo push. The full goal remains active.\n')
print(head)
