[package]
name = "ruffini_hyper_polynomial_pilot"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "ruffini_hyper_polynomial_pilot"
path = "main.rs"

[dependencies]
hyperreal = { path = "snapshot/hyperreal" }
hyperlimit = { path = "snapshot/hyperlimit" }
num = "0.4.3"

[features]
allocation-profile = []

[workspace]
