[package]
name = "calcium-point-qualified-platform-candidate"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
hyperreal = { path = "../point-image-qualified-candidate/hyperreal" }
hyperlimit = { path = "../point-image-qualified-candidate/hyperlimit" }
hypersolve = { path = "../point-image-qualified-candidate/hypersolve" }
serde_json = "1.0"
[lib]
crate-type = ["cdylib"]
path = "../point-qualified-platform.rs"
[[bin]]
name = "point-qualified-platform-candidate"
path = "../point-qualified-platform.rs"
