[package]
name = "calcium-point-image-cost-candidate"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
hyperreal = { path = "../point-image-candidate/hyperreal", default-features = false }
hyperlimit = { path = "../point-image-candidate/hyperlimit", default-features = false }
hypersolve = { path = "../point-image-candidate/hypersolve", default-features = false }
serde_json = "1.0.149"
[[bin]]
name = "calcium-point-image-candidate-cpu"
path = "../power-sums-cpu.rs"
[[bin]]
name = "calcium-point-image-candidate-allocation"
path = "../power-sums-allocation.rs"
