[package]
name = "calcium-root-exp-sign-bench"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[features]
allocation-count = []

[dependencies]
hyperreal = { path = "../root-exp-sign-trial-hyperreal" }
num = "0.4.3"

[[bin]]
name = "calcium-root-exp-sign-bench"
path = "../root-exp-bench.rs"
