module Functions (sbfPi, sbfExpFn, sbfSin, sbfCos, sbfSqrt, sbfArctan,
		  sbfLn, sbfExpon) 
	where

import Utils
import SBinStream
import SBinFloat
import SBinDec
import IReal
import X_Repn


-- ************************************************************

-- Computes next iteration
sqrt_it :: SBinFloat -> SBinFloat -> SBinFloat
sqrt_it x y  = (sbfAv y (sbfDiv x y))


-- nth approximation ...
sqrt_nth :: SBinFloat -> Int -> SBinFloat
--sqrt_nth x 0 = x
sqrt_nth x 0 = sbfGen (sqrt (sbfEval x 25)) 
    -- Bit of a cheat. Is this good enough?
    -- Problem: Make sure the first approximation is on the right side.
    --          Poss. add/subtract greatest poss. error?
sqrt_nth x n = sqrt_it x (sqrt_nth x (n-1))


-- Produces list of iterations
sqrt_i x y = ((y'', y'): sqrt_i x y')
	where {y'  = sqrt_it x y;
	       y'' = sbfSub (sbfShl y' 1) y}


-- 
sqrt_iterator x = sqrt_i x (sqrt_nth x 2)


sbfSqrt = sbfLimit.sqrt_iterator


-- ************************************************************
-- ln (1+x) where (-1 < x <= 1)

-- Need to scale input into this range first.


-- Uses f

-- Computes next iteration
ln_one_plus_x_it :: SBinFloat -> SBinFloat -> Int -> SBinFloat
ln_one_plus_x_it x y n = sbfIntDiv (sbfMul x y) n


-- Produces list of iterations
-- Will Fail for x<=0
ln_one_plus_x_i :: SBinFloat -> SBinFloat -> SBinFloat -> Int -> IReal
ln_one_plus_x_i x xn y n | even n = ((y',y):ln_one_plus_x_i x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfSub y (sbfIntDiv xn' n)}
ln_one_plus_x_i x xn y n | odd n  = ((y,y'):ln_one_plus_x_i x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfAdd y (sbfIntDiv xn' n)}



-- Test idea of getting x in -1/2, 1/2, and then using take.
-- This allows exponents of x<1 to be taken
ln_one_plus_x_i2 ::  SBinFloat -> SBinFloat -> SBinFloat 
				 -> Int -> IReal
ln_one_plus_x_i2 x xn y n = ((ylow,yhigh):ln_one_plus_x_i2 x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'@(e,m) = if (even n) then sbfSub y (sbfIntDiv xn' n)
		                      else sbfAdd y (sbfIntDiv xn' n);
	       ylow     = (e, (take (n+(toInt e)) m) ++ sbminusOne);
	       yhigh    = (e, (take (n+(toInt e)) m) ++ sbOne)}




ln_one_plus_x_i' x xn y n | even n = ((sbfEval y' 10,sbfEval y 10):ln_one_plus_x_i' x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfSub y (sbfIntDiv xn' n)}
ln_one_plus_x_i' x xn y n | odd n  = ((sbfEval y 10,sbfEval y' 10):ln_one_plus_x_i' x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfAdd y (sbfIntDiv xn' n)}



-- 
ln_one_plus_x_iterator' x = ln_one_plus_x_i' x sbfOne sbfZero 1


ln_one_plus_x_iterator :: SBinFloat -> IReal
ln_one_plus_x_iterator x = ln_one_plus_x_i2 x sbfOne sbfZero 1
--ln_one_plus_x_iterator2 x = ln_one_plus_x_i2 x sbfOne sbfZero 1


--sbfLn''' = sbfBetween.ln_one_plus_x_iterator
sbfLn''' :: SBinFloat -> SBinFloat
sbfLn''' = sbfLimit.ln_one_plus_x_iterator

sbfLn'' :: SBinFloat -> SBinFloat
sbfLn'' x = sbfLn''' (sbfSub x sbfOne)


-- Need to ensure that any number can be placed in [1/2, 3/2] by 
--   multiplying or dividing by exp(1).

-- Order is important here. The algorithm looks for cases where either 
--   x, x.e, or x/e can be confirmed to be in [1/2,3/2].

-- This function that normalisation has been performed that guarantees that
--   numbers starting (1:-1:_) or (0:_) have all been modified.

sbfLn' (_,(-1:_))        = undefined
sbfLn' x@(-1,(1:  1:_))  = sbfSub (sbfLn'' (sbfNormAllowNegExp    
				   (sbfMul x (sbfExpFn sbfOne)))) sbfOne
sbfLn' x@(0,(1:  0: a: b: c: _))  = 
       if ((a == -1) ||
	  ((a ==  0) && ((b == -1) ||
		        ((b ==  0) && (c /= 1))))) then
         sbfSub (sbfLn'' (sbfNormAllowNegExp    
				   (sbfMul x (sbfExpFn sbfOne)))) sbfOne

       else (sbfLn'' x) 
sbfLn' x@(0,(1:  1:_))  = (sbfLn'' x)  -- [1/2, 1]
sbfLn' x@(1,(1:  _))    = (sbfLn'' x)  -- [1/2,3/2]
sbfLn' x@(2,(1:  0: -1: -1: _)) = (sbfLn'' x)
sbfLn' x@(2,(1:  0: -1: 0: -1: _)) = (sbfLn'' x)
sbfLn' x@(2,(1:  0: _)) = sbfAdd (sbfLn'' (sbfNormAllowNegExp 
				   (sbfDiv x (sbfExpFn sbfOne)))) sbfOne

sbfLn' x@(e,_) | e >= 1 = sbfAdd (sbfLn' (sbfNormAllowNegExp 
				   (sbfDiv x (sbfExpFn sbfOne)))) sbfOne
 	       | e <  1 = sbfSub (sbfLn' (sbfNormAllowNegExp 
				   (xsbfMul x (sbfExpFn sbfOne)))) sbfOne


sbfLn x = sbfLn' (sbfNormAllowNegExpExtra x)
-- ************************************************************


{- 
-- Exponential Function. Computed using the limit of the series
-- generated by

  s(x,0) = 1
  s(x,n) = x.s(n)/ n

Hence:
  s(x,i) = x^i/i!  

And:
  exp(x)   = Sum(i=0..inf, s(x,i))

-}


-- exp_it : Compute s(x,n) 
--          y = s(x,n-1), s(x,n) = x * s(x,n-1) / n
exp_it :: SBinFloat -> SBinFloat -> Int -> SBinFloat
exp_it x y n  = sbfIntDiv (sbfMul x y) n


-- exp_pos_bounds : Compute upper and lower bounds of 
--                  Sum(i=0..n, s(x,i)), given x > 0, s(n) <= 1
--                  Lower limit = Sum(i=0..n, s(x,i))
--                  Upper limit = Sum(i=0..n, s(x,i)) + s(x,n)
--                     y = s(x,n)
--                     t = Sum(i=0..n, s(x,i))
exp_pos_bounds :: SBinFloat -> SBinFloat -> Int -> SbInterval
exp_pos_bounds y t n = (lower, upper)
	where {lower = sbfAdd y t;
	       upper = sbfAdd y lower}



-- exp_neg_bounds : Compute upper and lower bounds of 
--                  Sum(i=0..n, s(x,i)), given x < 0
--                  This value oscillates round the limit
--                     y = s(x,n)
--                     t = Sum(i=0..n, s(x,i))
exp_neg_bounds :: SBinFloat -> SBinFloat -> Int -> SbInterval
exp_neg_bounds y t n | odd n    = (t', t)
		     | otherwise = (t,  t')
	where t'  = sbfAdd y t;



-- exp_uk_bounds : Compute upper and lower bounds of 
--                  Sum(i=0..n, s(x,i)), given, s(n) <= 1
--                  Limits union of exp_neg_bounds and exp_pos_bounds.
--                     y = s(x,n)
--                     t = Sum(i=0..n, s(x,i))
exp_uk_bounds :: SBinFloat -> SBinFloat -> Int -> (SbInterval, SBinFloat)
exp_uk_bounds y t n = ((sbfMin t (sbfMin t' t''), sbfMax t (sbfMax t' t'')),t')
	where {t'  = sbfAdd y t;
	       t'' = sbfAdd y t'}



-- exp_elt1 :  Iterate until exponent of s(n) < 1.
--             Required to get upper bounds if x>0
--               x : Original parameter from exp(x)
--               y : s(n-1)
--               t : Sum(i=0..n-1, s(i))
--               n : Iteration number. Needed as s(n) = x * s(n-1) / n
--             Note: This may be a *very* slow way of doing this for big x 
--                   exp(6.45) takes 15-16 iterations.
exp_elt1 :: SBinFloat -> SBinFloat -> SBinFloat -> Int
		      -> (SBinFloat,SBinFloat,Int)
exp_elt1 x y@(e,m) t n | e<1       = (y,t,n)
exp_elt1 x y       t n | otherwise = exp_elt1 x y' t' (n+1)
	where {y' = sbfNorm (exp_it x y n);
	       t' = sbfAdd y' t}


-- exp_pos_i : Generate continuation of IReal for x>0
--               x : Original parameter from exp(x) 
--               y : s(n-1)
--               t : Sum(i=0..n-1, s(i))
--               n : Iteration number. Needed as s(n) = x * s(n-1) / n
exp_pos_i :: SBinFloat -> SBinFloat -> SBinFloat -> Int -> IReal
exp_pos_i x y t n = (b: exp_pos_i x y' low (n+1))
	where {y' = exp_it x y n;                 -- Compute s(n)
	       b@(low,upp) = exp_pos_bounds y' t n}   



-- exp_neg_i : Generate continuation of IReal for x<0
--               x : Original parameter from exp(x) 
--               y : s(n-1)
--               t : Sum(i=0..n-1, s(i))
--               n : Iteration number. Needed as s(n) = x * s(n-1) / n
exp_neg_i :: SBinFloat -> SBinFloat -> SBinFloat -> Int -> IReal
exp_neg_i x y t n | odd n      = (b: exp_neg_i x y' low (n+1))
		  | otherwise  = (b: exp_neg_i x y' upp (n+1))
	where {y' = exp_it x y n;
	       b@(low,upp) = exp_neg_bounds y' t n}


-- exp_uk_i : Generate continuation of IReal for sign of x unknown
--               x : Original parameter from exp(x) 
--               y : s(n-1)
--               t : Sum(i=0..n-1, s(i))
--               n : Iteration number. Needed as s(n) = x * s(n-1) / n
exp_uk_i :: SBinFloat -> SBinFloat -> SBinFloat -> Int -> IReal
exp_uk_i x y t n = (b: exp_uk_i x y' t' (n+1))
	where {y' = exp_it x y n;
	       (b@(low,upp),t') = exp_uk_bounds y' t n}


-- exp_pos_iterator : Generate IReal for exp(x) given x>0
--                    First necessary to iterate sequence till s(n) <= 1
exp_pos_iterator :: SBinFloat -> IReal
exp_pos_iterator x = exp_pos_i x y t n
	where (y,t,n) = exp_elt1 x x (sbfAdd sbfOne x) 2


-- exp_neg_iterator : Generate IReal for exp(x) given x<0
exp_neg_iterator :: SBinFloat -> IReal
exp_neg_iterator x = exp_neg_i x x (sbfAdd sbfOne x) 2


-- exp_pos_iterator : Generate IReal for exp(x) given x>0
--                    Assumes that (x <= 1) ==> (s(n) <= 1)
--		      This assumption is safe because we'll only use this
--                    if normalisation reveals x approx. = 0
exp_uk_iterator :: SBinFloat -> IReal
exp_uk_iterator x = exp_uk_i x y t n
	where (y,t,n) = exp_elt1 x x (sbfAdd sbfOne x) 2


sbfExpFn :: SBinFloat -> SBinFloat
sbfExpFn x = case a of 
	    1 ->  sbfLimit (exp_pos_iterator x')
	    0 ->  sbfLimit (exp_uk_iterator  x')
	    -1 -> sbfLimit (exp_neg_iterator x')
	 where x'@(_,(a:_)) = sbfNormMaxOrExp_lte_0 x 10




-- sbfExpon: Exponentiation (ie. x^y)
sbfExpon :: SBinFloat -> SBinFloat -> SBinFloat
sbfExpon x y = sbfExpFn (sbfMul (sbfLn x) y)



-- ************************************************************


-- Fails on negative numbers because bounds are the wrong way round.
-- Will fail on zero due to normalisation
-- Significantly slower for |x| > 1
sin_i x2 y s n | odd n     = ((y', y): sin_i x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n)*(2*n+1));
	       y' = sbfNorm (sbfSub y s')}
sin_i x2 y s n | otherwise = ((y, y'): sin_i x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n)*(2*n+1));
	       y' = sbfNorm (sbfAdd y s')}



sin_iterator x = sin_i (sbfMul x x) x x 1

-- ** Normalise here **? 
sbfSin x = sbfBetween (sin_iterator x)



-- ************************************************************


-- Fails on negative numbers because bounds are the wrong way round.
-- Will fail on zero due to normalisation
-- Significantly slower for |x| > 1
cos_i x2 y s n | odd n     = ((y', y): cos_i x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n-1)*(2*n));
	       y' = sbfNorm (sbfSub y s')}
cos_i x2 y s n | otherwise = ((y, y'): cos_i x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n-1)*(2*n));
	       y' = sbfNorm (sbfAdd y s')}
{-
cos_i' x2 y s n | odd n     = ((sbfEval y' 25,sbfEval y 25): cos_i' x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n-1)*(2*n));
	       y' = sbfNorm (sbfSub y s')}
cos_i' x2 y s n | otherwise = ((sbfEval y 25,sbfEval y' 25): cos_i' x2 y' s' (n+1))
	where {s' = sbfIntDiv (sbfMul x2 s) ((2*n-1)*(2*n));
	       y' = sbfNorm (sbfAdd y s')}
-}


cos_iterator x = cos_i (sbfMul x x) sbfOne sbfOne 1

sbfCos = sbfLimit.cos_iterator



-- ************************************************************

-- Stupidly slow ... as before with Pi ...

arctan_i x2 y s n | odd n     = ((y', y): arctan_i x2 y' s' (n+1))
	where {s'  = sbfMul x2 s;
	       s'' = sbfIntDiv s' (2*n+1);
	       y'  = sbfNorm (sbfSub y s'')}
arctan_i x2 y s n | otherwise = ((y, y'): arctan_i x2 y' s' (n+1))
	where {s'  = sbfMul x2 s;
	       s'' = sbfIntDiv s' (2*n+1);
	       y' = sbfNorm (sbfAdd y s'')}


arctan_iterator x = arctan_i (sbfMul x x) x x 1

--sbfArctan = sbfLimit.arctan_iterator

-- Test of arctan using betweeness.
sbfArctan = sbfBetween.barctan_iterator


-- Test of same for betweeness
barctan_i x2 y s n = ((y, y'): barctan_i x2 y' s' (n+1))
	where {s'  = sbfMul x2 s;
	       s'' = sbfIntDiv s' (2*n+1);
	       y'  = sbfNorm (if (odd n) then sbfSub y s'' else sbfAdd y s'')}

barctan_i' x2 y s n = ((sbfDec y 10, sbfDec y' 10): barctan_i' x2 y' s' (n+1))
	where {s'  = sbfMul x2 s;
	       s'' = sbfIntDiv s' (2*n+1);
	       y'  = sbfNorm (if (odd n) then sbfSub y s'' else sbfAdd y s'')}

barctan_iterator x = barctan_i (sbfMul x x) x x 1



-- ************************************************************

-- pi/4 = arctan(1/2) + arctan(1/3)
--sbfPi = sbfShl (sbfAdd (sbfArctan sbfHalf) (sbfArctan sbfThird)) 2


-- pi/4 = 4 * arctan(1/5) - arctan(1/239)
{-
sbfPi = sbfShl (sbfSub (sbfShl (sbfArctan (sbfIntDiv sbfOne 5)) 2) 
  		          (sbfArctan (sbfIntDiv sbfOne 239))) 2
-}


-- pi = 24 * (arctan(1/8)) + 8 * (arctan(1/57)) + 4 * (arctan(1/239))

sbf24 = (5, (1: 1: sbZero)) :: SBinFloat
sb1over57 = (0: 0: 0: 0: 0: 1: 0: 0: 0: 1: 1: 1: 1: 1: 0: 1: 1: 1:
			sb1over57) :: SBinStream
sbf1over57 = (0,sb1over57)  :: SBinFloat
	-- Pretty sure this is right, but it's just observation
-- sbf1over57 = (sbfIntDiv sbfOne 57) :: SBinFloat

sbfPi = sbfAdd (sbfAdd (sbfMul (sbfArctan sbfEighth) sbf24)
		       (sbfShl (sbfArctan (sbf1over57)) 3))
	       (sbfShl (sbfArctan (sbfIntDiv sbfOne 239)) 2)



{-
-- pi = 20 * arctan(1/7) + 16 * (arctan (1/53)) + 2 * (arctan (1/4443))

sbf20 = (5, (1: 0: 1: sbZero))

sbfPi = sbfAdd (sbfAdd (sbfMul (sbfArctan (sbfIntDiv sbfOne 7)) sbf20)
		       (sbfShl (sbfArctan (sbfIntDiv sbfOne 53)) 4))
	       (sbfShl (sbfArctan (sbfIntDiv sbfOne 4443)) 3)
-}







-- ************************************************************
-- ln (1+x) where (-1 < x <= 1)

-- Need to scale input into this range first.


-- Uses f

-- Computes next iteration
ln_it :: SBinFloat -> SBinFloat -> Int -> SBinFloat
ln_it x y n = sbfIntDiv (sbfMul x y) n


-- Produces list of iterations
ln_i :: SBinFloat -> SBinFloat -> SBinFloat -> Int -> IReal
ln_i x xn y n | even n = ((y',y):ln_i x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfSub y (sbfIntDiv xn' n)}
ln_i x xn y n | odd n  = ((y,y'):ln_i x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfAdd y (sbfIntDiv xn' n)}



ln_i' x xn y n | even n = ((sbfEval y' 10,sbfEval y 10):ln_i' x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfSub y (sbfIntDiv xn' n)}
ln_i' x xn y n | odd n  = ((sbfEval y 10,sbfEval y' 10):ln_i' x xn' y' (n+1))
	where {xn' = sbfMul x xn;
	       y'  = sbfAdd y (sbfIntDiv xn' n)}



-- 
ln_iterator' x = ln_i' x sbfOne sbfZero 1


ln_iterator :: SBinFloat -> IReal
ln_iterator x = ln_i x sbfOne sbfZero 1


--sbfLn = sbfBetween.ln_iterator
--sbfLn = sbfLimit.ln_iterator
