[package]
name = "aern-finite-oracle"
version = "0.0.0"
edition = "2024"

[dependencies]
hyperreal = { path = "../hyperreal-candidate" }
num = "0.4.3"
num-bigint = "=0.4.6"
rug = { version = "=1.30.0", default-features = false, features = ["rational", "std"] }

[[bin]]
name = "aern-finite-oracle"
path = "../finite-oracle.rs"

[workspace]
