[package]
name = "escardo-qualification"
version = "0.0.0"
edition = "2024"
publish = false
autobins = false

[dependencies]
hyperreal = { path = "../../hyperreal" }
num = { version = "0.4.3", features = ["num-bigint"] }
rug = { version = "1.30.0", default-features = false, features = ["float", "integer", "rational", "std"] }

[[bin]]
name = "escardo_oracle"
path = "escardo_oracle.rs"

[profile.release]
debug = 0
incremental = false
codegen-units = 16
